[package]
name = "sdl2_backend"
version = "0.0.0"
edition = "2024"

[dependencies]
log = { workspace = true }
indexmap = { workspace = true }
sdl2-sys = { workspace = true }
sdl2 = { workspace = true }

common = { path = "../common" }
