[workspace]
resolver = "3"
members = [
    "common",
    "render",
    "physics",
    "engine",
]

[workspace.dependencies]
log = "0.4"
indexmap = "2.12"
sdl2-sys = "0.38"
sdl2 = { version = "0.38", features = ["bundled"] }
